### ISSUE TITLE
Remove API docs

### ISSUE THREAD

**Issue by QuLogic** [obspy/docs#5]
API is on the webpage, attached to the release, or can be built from the source. Is there really any need to keep it in this repository? Maybe it can be rebased out?

**Comment by QuLogic** [comment]
Also, if you don't mind stripping it out entirely, then `posters/2013_egu/.svn/` should be deleted, too.

**Comment by megies** [comment]
Yeah, API can be deleted. Also rebased out if you want. We put it here at a time when it was not yet possible to attach files to a github release.

**Comment by QuLogic** [comment]
Does anything depend on it? I'd probably just strip it out after merging #6, then.

**Comment by megies** [comment]
> Does anything depend on it? I'd probably just strip it out after merging #6, then.

I don't think so. Go ahead.

**Comment by QuLogic** [comment]
This is done now; everyone please remember to re-clone.

**Comment by megies** [comment]
> everyone please remember to re-clone.

or `git stash save; git fetch; git reset origin/master`..
